Все сломалось
Type: <class 'KeyboardInterrupt'>
Value: 
Traceback:   File "/home/valera/PycharmProjects/gorodsredaparse/main.py", line 48, in <module>
    marker_data = get_data(i)

  File "/home/valera/PycharmProjects/gorodsredaparse/main.py", line 29, in get_data
    response = requests.request("GET", url, headers=headers, data=payload)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):

  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
Все сломалось
Type: <class 'KeyboardInterrupt'>
Value: 
Traceback:   File "/home/valera/PycharmProjects/gorodsredaparse/main.py", line 50, in <module>
    marker_data = get_data(i)

  File "/home/valera/PycharmProjects/gorodsredaparse/main.py", line 29, in get_data
    response = requests.request("GET", url, headers=headers, data=payload)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):

  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
Все сломалось
Type: <class 'KeyboardInterrupt'>
Value: 
Traceback:   File "/home/valera/PycharmProjects/gorodsredaparse/main.py", line 68, in <module>
    marker_data = get_data(i)

  File "/home/valera/PycharmProjects/gorodsredaparse/main.py", line 30, in get_data
    response = requests.request("GET", url, headers=headers, data=payload)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):

  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
Все сломалось
Type: <class 'KeyboardInterrupt'>
Value: 
Traceback:   File "/home/valera/PycharmProjects/gorodsredaparse/main.py", line 76, in <module>
    marker_data = get_data(i)

  File "/home/valera/PycharmProjects/gorodsredaparse/main.py", line 30, in get_data
    response = requests.request("GET", url, headers=headers, data=payload)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):

  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
Все сломалось
Type: <class 'KeyboardInterrupt'>
Value: 
Traceback:   File "/home/valera/PycharmProjects/gorodsredaparse/main.py", line 85, in <module>
    marker_data = get_data(i)

  File "/home/valera/PycharmProjects/gorodsredaparse/main.py", line 29, in get_data
    response = requests.request("GET", url, headers=headers, data=payload)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)

  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(

  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()

  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
Все сломалось
Type: <class 'KeyboardInterrupt'>
Value: 
Traceback:   File "/home/valera/PycharmProjects/gorodsredaparse/main.py", line 85, in <module>
    marker_data = get_data(i)

  File "/home/valera/PycharmProjects/gorodsredaparse/main.py", line 29, in get_data
    response = requests.request("GET", url, headers=headers, data=payload)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):

  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
Все сломалось
Type: <class 'KeyboardInterrupt'>
Value: 
Traceback:   File "/home/valera/PycharmProjects/gorodsredaparse/main.py", line 89, in <module>
    dump_in_json_file(list, PATH_TO_JSON_FILE)

  File "/home/valera/PycharmProjects/gorodsredaparse/main.py", line 57, in dump_in_json_file
    json.dump(data, file, ensure_ascii=False, indent=4)

  File "/usr/lib/python3.8/json/__init__.py", line 180, in dump
    fp.write(chunk)
Все сломалось
Type: <class 'json.decoder.JSONDecodeError'>
Value: Expecting property name enclosed in double quotes: line 66030 column 25 (char 3305814)
Traceback:   File "/home/valera/PycharmProjects/gorodsredaparse/main.py", line 61, in <module>
    file_data = unpack_data_from_json_file(PATH_TO_JSON_FILE)

  File "/home/valera/PycharmProjects/gorodsredaparse/main.py", line 51, in unpack_data_from_json_file
    file_info = json.load(file)

  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),

  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)

  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
Все сломалось
Type: <class 'KeyboardInterrupt'>
Value: 
Traceback:   File "/home/valera/PycharmProjects/gorodsredaparse/main.py", line 87, in <module>
    marker_data = get_data(i)

  File "/home/valera/PycharmProjects/gorodsredaparse/main.py", line 29, in get_data
    response = requests.request("GET", url, headers=headers, data=payload)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)

  File "<string>", line 3, in raise_from

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()

  File "/usr/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()

  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()

  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")

  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)

  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)

  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
Все сломалось
Type: <class 'IndexError'>
Value: list index out of range
Traceback:   File "/home/valera/PycharmProjects/gorodsredaparse/main.py", line 73, in <module>
    start_number = int(list_of_id[-1]) + 1
Все сломалось
Type: <class 'KeyboardInterrupt'>
Value: 
Traceback:   File "/home/valera/PycharmProjects/gorodsredaparse/main.py", line 90, in <module>
    marker_data = get_data(i)

  File "/home/valera/PycharmProjects/gorodsredaparse/main.py", line 29, in get_data
    response = requests.request("GET", url, headers=headers, data=payload)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):

  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
Все сломалось
Type: <class 'KeyboardInterrupt'>
Value: 
Traceback:   File "/home/valera/PycharmProjects/gorodsredaparse/main.py", line 90, in <module>
    logger.info(f'Номер записи: {i}')

  File "/home/valera/PycharmProjects/gorodsredaparse/main.py", line 29, in get_data
    }

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):

  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
Все сломалось
Type: <class 'KeyboardInterrupt'>
Value: 
Traceback:   File "/home/valera/PycharmProjects/gorodsredaparse/main.py", line 91, in <module>
    marker_data = get_data(i)

  File "/home/valera/PycharmProjects/gorodsredaparse/main.py", line 30, in get_data
    response = requests.request("GET", url, headers=headers, data=payload)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)

  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(

  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()

  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
Все сломалось
Type: <class 'KeyboardInterrupt'>
Value: 
Traceback:   File "/home/valera/PycharmProjects/gorodsredaparse/main.py", line 93, in <module>
    dump_in_json_file(list, PATH_TO_JSON_FILE)

  File "/home/valera/PycharmProjects/gorodsredaparse/main.py", line 58, in dump_in_json_file
    json.dump(data, file, ensure_ascii=False, indent=4)

  File "/usr/lib/python3.8/json/__init__.py", line 179, in dump
    for chunk in iterable:
Все сломалось
Type: <class 'KeyboardInterrupt'>
Value: 
Traceback:   File "/home/valera/PycharmProjects/gorodsredaparse/main.py", line 91, in <module>
    marker_data = get_data(i)

  File "/home/valera/PycharmProjects/gorodsredaparse/main.py", line 30, in get_data
    response = requests.request("GET", url, headers=headers, data=payload)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(

  File "/home/valera/PycharmProjects/gorodsredaparse/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):

  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
